name: thaiclock_web
description: "A new Flutter project for Web."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  image_picker: ^1.2.3
  path_provider: ^2.1.6
  web: ^1.0.0
  url_launcher: ^6.3.2
  video_player: ^2.8.2  # ← dependencies の下に引っ越し！

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - web/images/  # これで web/images/ 内の demo.mp4 も一緒に読み込まれます！

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"